# JBrowse

#

FROM flatfile_jbrowse:latest as build

ARG ACCESSKEY
ARG SECRETKEY
ARG RELEASE

#agr_jbrowse_config contains the configuration files for the various species; they are
#moved into the right place in the long RUN command below
#RUN git clone --single-branch --branch release-3.1.1 https://github.com/alliance-genome/agr_jbrowse_config.git
RUN git clone --single-branch --branch gff_processing https://github.com/alliance-genome/agr_jbrowse_config.git


#RUN mkdir /data

WORKDIR /jbrowse

RUN /agr_jbrowse_config/scripts/fetch_gff.sh

#run it, passing in access and secret keys and AGR release
RUN /agr_jbrowse_config/scripts/build_controler.pl --release $RELEASE  --awsaccess $ACCESSKEY --awssecret $SECRETKEY


#COPY docker-entrypoint.sh /
#CMD ["/docker-entrypoint.sh"]
